[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "alphazero"
version = "0.1.0"
requires-python = ">=3.8"
# Do not list requirements here if you're using requirements.txt

[tool.setuptools.packages.find]
where = ["."]
