export default {
  ".typo-giga-title": {
    fontWeight: "500",
    fontSize: "16rem",
    fontStyle: "normal",
    lineHeight: "20rem",
  },
  ".typo-mega-title": {
    fontWeight: "500",
    fontSize: "12rem",
    fontStyle: "normal",
    lineHeight: "16rem",
  },
  ".typo-extra-large-title": {
    fontWeight: "500",
    fontSize: "10rem",
    fontStyle: "normal",
    lineHeight: "14rem",
  },
  ".typo-large-title": {
    fontWeight: "500",
    fontSize: "8rem",
    fontStyle: "normal",
    lineHeight: "12rem",
  },
  ".typo-title": {
    fontWeight: "500",
    fontSize: "7rem",
    fontStyle: "normal",
    lineHeight: "10rem",
  },
  ".typo-headline-bold": {
    fontWeight: "500",
    fontSize: "5rem",
    fontStyle: "normal",
    lineHeight: "8rem",
  },
  ".typo-headline": {
    fontWeight: "400",
    fontSize: "5rem",
    fontStyle: "normal",
    lineHeight: "8rem",
  },
  ".typo-callout": {
    fontWeight: "400",
    fontSize: "4rem",
    fontStyle: "normal",
    lineHeight: "6rem",
    textTransform: "uppercase",
  },
  ".typo-body-bold": {
    fontWeight: "500",
    fontSize: "4rem",
    fontStyle: "normal",
    lineHeight: "6rem",
  },
  ".typo-body": {
    fontWeight: "400",
    fontSize: "4rem",
    fontStyle: "normal",
    lineHeight: "6rem",
  },
  ".typo-sub-text-bold": {
    fontWeight: "500",
    fontSize: "3rem",
    fontStyle: "normal",
    lineHeight: "5rem",
  },
  ".typo-sub-text": {
    fontWeight: "400",
    fontSize: "3rem",
    fontStyle: "normal",
    lineHeight: "5rem",
  },
  ".typo-caption-bold": {
    fontWeight: "500",
    fontSize: "12px",
    fontStyle: "normal",
    lineHeight: "4rem",
  },
  ".typo-caption": {
    fontWeight: "400",
    fontSize: "12px",
    fontStyle: "normal",
    lineHeight: "4rem",
  },
};
